version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
      MYSQL_DATABASE: product

  spring-app-starter:
    build:
      context: ../lbg-car-spring-app-starter
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product
      SPRING_DATASOURCE_USERNAME: product_user
      SPRING_DATASOURCE_PASSWORD: product_user_password

  car-react-starter:
    build:
      context: ../lbg-car-react-starter
      dockerfile: Dockerfile
    ports:
      - "3000:80"